version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  test_and_build_docs:
    docker:
      - image: libmir/circle-dlang
    parameters:
      to:
        description: "Folder with generated docs"
        type: string
        default: web
    steps:
      - checkout
      - run: cp -r /repo/* ./  && cat meson.build.1 >> meson.build
      - run: meson _build_dir_ --default-library=static -D with_test=true -D with_doc=true
      - run: ninja -C _build_dir_ test -j1
      - run: cp -r _build_dir_/web <<parameters.to>> && rm -rf _build_dir_
      - persist_to_workspace:
          root: ~/project
          paths:
            - <<parameters.to>>
  upload_docs:
    docker:
      - image: circleci/python:latest
    parameters:
      to:
        description: "S3 domain"
        type: string
      from:
        description: "Folder with generated docs"
        type: string
        default: web
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          from: <<parameters.from>>
          to: s3://<<parameters.to>>
          overwrite: true
